title:            GBD.Rpi2.Gentoo
description:      "GBD Raspberry Pi 2 Gentoo Overlay"
logo:             site_logo.png
disqus_shortname: gbd_web_project_template

# Change baseurl to the leading path after the domain
# see http://jekyllrb.com/docs/github-pages/
# to override Start Jekyll with: jekyll serve --baseurl ''
baseurl: /GBD.Rpi2.Gentoo

# GitHub Url for the project this page refereces
projecturl: https://github.com/grbd/GBD.Rpi2.Gentoo

# Use the redcarpet renderer for code blocks and tables, also pygments for code blocks
markdown:    redcarpet
highlighter: pygments

redcarpet:
  extensions: [tables,autolink]

# Include .nojekyll so that the final rendered page isn't re-rendered by github's jekyll which doesn't have plugins
include: [".nojekyll"]
exclude: ["deploy.bat","build.bat","build-watch.bat","todo.md"]
